apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: podinfo
  namespace: cluster-config
spec:
  imageRepositoryRef:
    name: podinfo
  policy:
    semver:
      range: 6.3.x